"""CLI command to seed example Second Brain notes."""

import asyncio

import click

from app.commands import command, success

SEED_NOTES = [
    ("Postgres pgvector migration plan",
     "Steps to migrate vector store to pgvector:\n"
     "1. Enable pgvector extension: CREATE EXTENSION vector;\n"
     "2. Create HNSW index for cosine similarity\n"
     "3. Migrate embeddings from ChromaDB\n"
     "4. Update connection string in .env\n"
     "5. Run integration tests",
     ["database", "devops", "migration"]),
    ("Auth flow decisions",
     "Decided on JWT access + refresh token pattern.\n"
     "Access token: 15min, stored in memory.\n"
     "Refresh token: 7 days, httpOnly cookie.\n"
     "API key auth for service-to-service via X-API-Key header.",
     ["auth", "architecture", "security"]),
    ("RAG chunking strategy",
     "Current settings:\n"
     "- Chunk size: 1024 tokens\n"
     "- Chunk overlap: 128 tokens\n"
     "- Separator priority: paragraphs > sentences > words\n"
     "Hybrid search enabled (BM25 + vector, RRF fusion).\n"
     "Reranker: Cohere rerank-v3.5 when available.",
     ["rag", "search", "config"]),
    ("Docker compose dev workflow",
     "make bootstrap = make dev + make seed\n"
     "Backend on 8080, frontend on 3030, docs on 8080/docs\n"
     "PostgreSQL 16, Redis 7, Adminer on 8081\n"
     "Hot reload enabled for backend and frontend",
     ["docker", "devops", "workflow"]),
    ("Agent tool registration pattern",
     "Tools registered in _register_tools() on AssistantAgent:\n"
     "- @agent.tool_plain for sync tools\n"
     "- @agent.tool for async tools with RunContext[Deps]\n"
     "Deps carries user_id, organization_id, kb_collection_names.\n"
     "Tools can boot their own AsyncSession via async_session_maker().",
     ["agent", "architecture", "patterns"]),
    ("Frontend stack overview",
     "Next.js 15 App Router with i18n (PL/EN)\n"
     "Zustand for client state, TanStack Query for server state\n"
     "WebSocket for real-time chat\n"
     "shadcn/ui components (Radix primitives + Tailwind)\n"
     "API calls go through Next.js route handlers → proxy to FastAPI",
     ["frontend", "architecture"]),
    ("Deployment checklist",
     "Pre-deploy:\n"
     "- Set ENVIRONMENT=production\n"
     "- Rotate SECRET_KEY\n"
     "- Set real SMTP credentials\n"
     "- Configure Sentry DSN\n"
     "- Run alembic upgrade head\n"
     "- Verify health check endpoint",
     ["deployment", "devops", "checklist"]),
    ("Team onboarding notes",
     "New developer setup:\n"
     "1. Clone repo, run make bootstrap\n"
     "2. Register at /register with company email\n"
     "3. Get invited to org by admin\n"
     "4. Set up Voyage API key for embeddings\n"
     "5. Run seed-instructions for agent templates",
     ["onboarding", "team", "devops"]),
    ("API key management",
     "API keys use prefix-based lookup: sk_<43 chars>\n"
     "Stored as bcrypt hash, compared with secrets.compare_digest\n"
     "Scoped to user, no expiration by default.\n"
     "Header: X-API-Key\n"
     "Created via /me/slash-commands endpoint.",
     ["api", "security", "auth"]),
    ("Journal - Monday check-in",
     "Worked on the pgvector migration today. Got the extension "
     "enabled and created the first HNSW index. Hit a snag with "
     "the collection name validation — UUIDs have hyphens which "
     "aren't allowed in pgvector collection names. Fixed by "
     "stripping hyphens. Also set up the Voyage AI embedding key.",
     ["journal"]),
    ("Journal - Tuesday reflection",
     "Spent the morning debugging the migration issue. The "
     "autogenerated alembic migration captured every table instead "
     "of just the new ones. Lesson learned: always check "
     "autogenerated migrations before applying. Wrote custom "
     "manual migrations for 0019 and 0020. Much cleaner.",
     ["journal"]),
    ("Journal - Wednesday wins",
     "The rate limit issue was the last blocker. Voyage free tier "
     "is 3 RPM which made seeding slow. Added a delay between "
     "embedding calls. Everything works end-to-end now: notes get "
     "created in SQL, embedded into pgvector, and searchable via "
     "the agent. Ready to move on to the next feature.",
     ["journal"]),
    ("Next feature ideas",
     "Second Brain v2.0+ roadmap:\n"
     "- Daily journal with AI prompts\n"
     "- Note-to-note backlinks (bi-directional)\n"
     "- Weekly summary generation (celery task)\n"
     "- Tag auto-suggestion via LLM\n"
     "- Semantic note clustering\n"
     "- Forgotten note surface (notes older than 90 days)",
     ["roadmap", "features", "ideas"]),
]


@command("seed-notes", help="Seed example Second Brain notes for all users")
@click.option("--user-id", "-u", type=str, default=None,
              help="Seed for a specific user only")
def seed_notes(user_id: str | None) -> None:
    from uuid import UUID
    from sqlalchemy import select
    from app.db.models.user import User
    from app.db.session import async_session_maker
    from app.schemas.note import NoteCreate
    from app.services.note import NoteService

    async def _run() -> None:
        async with async_session_maker() as db:
            if user_id:
                result = await db.execute(
                    select(User).where(User.id == UUID(user_id)))
                users = result.scalars().all()
            else:
                result = await db.execute(select(User))
                users = result.scalars().all()

            if not users:
                click.echo("No users found. Register a user first.")
                return

            total = 0
            for user in users:
                service = NoteService(db)
                for title, content, tags in SEED_NOTES:
                    data = NoteCreate(title=title, content=content, tags=tags)
                    await service.create(user_id=user.id, data=data)
                    total += 1
                    await asyncio.sleep(22)  # Voyage free tier: 3 RPM

            click.echo(f"Seeded {total} notes across {len(users)} user(s).")

    asyncio.run(_run())
