
""""add_api_keys and email_digest"

Revision ID: b934cf556dfe
Revises: 0026_add_email_digest
Create Date: 2026-06-12 18:00:48.691193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b934cf556dfe'
down_revision: Union[str, None] = '0026_add_email_digest'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_organization_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_stripe_customer_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_stripe_subscription_id'), table_name='subscription')
    op.drop_index(op.f('subscription_status_idx'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('rag_sb_353de8cecd9a4ed69498d86f2fedb673_embedding_idx'), table_name='rag_sb_353de8cecd9a4ed69498d86f2fedb673', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('rag_sb_353de8cecd9a4ed69498d86f2fedb673')
    op.drop_index(op.f('ix_stripe_event_event_type'), table_name='stripe_event')
    op.drop_index(op.f('ix_stripe_event_stripe_event_id'), table_name='stripe_event')
    op.drop_table('stripe_event')
    op.drop_index(op.f('ix_agent_memories_user_id'), table_name='agent_memories')
    op.create_index(op.f('agent_memories_user_id_idx'), 'agent_memories', ['user_id'], unique=False)
    op.drop_column('agent_memories', 'embedding')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('api_keys_key_prefix_idx'), 'api_keys', ['key_prefix'], unique=True)
    op.create_index(op.f('api_keys_user_id_idx'), 'api_keys', ['user_id'], unique=False)
    op.drop_index(op.f('ix_audit_action'), table_name='app_admin_audit_logs')
    op.drop_index(op.f('ix_audit_actor_user_id'), table_name='app_admin_audit_logs')
    op.drop_index(op.f('ix_audit_organization_id'), table_name='app_admin_audit_logs')
    op.create_index(op.f('app_admin_audit_logs_action_idx'), 'app_admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('app_admin_audit_logs_actor_user_id_idx'), 'app_admin_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('app_admin_audit_logs_organization_id_idx'), 'app_admin_audit_logs', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_channel_bots_platform'), table_name='channel_bots')
    op.create_index(op.f('channel_bots_platform_idx'), 'channel_bots', ['platform'], unique=False)
    op.drop_index(op.f('ix_channel_identities_platform'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_platform_user_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_user_id'), table_name='channel_identities')
    op.create_index(op.f('channel_identities_platform_idx'), 'channel_identities', ['platform'], unique=False)
    op.create_index(op.f('channel_identities_platform_user_id_idx'), 'channel_identities', ['platform_user_id'], unique=False)
    op.create_index(op.f('channel_identities_user_id_idx'), 'channel_identities', ['user_id'], unique=False)
    op.drop_index(op.f('ix_channel_sessions_bot_id'), table_name='channel_sessions')
    op.drop_index(op.f('ix_channel_sessions_conversation_id'), table_name='channel_sessions')
    op.drop_index(op.f('ix_channel_sessions_identity_id'), table_name='channel_sessions')
    op.drop_index(op.f('ix_channel_sessions_platform_chat_id'), table_name='channel_sessions')
    op.create_index(op.f('channel_sessions_bot_id_idx'), 'channel_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('channel_sessions_conversation_id_idx'), 'channel_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('channel_sessions_identity_id_idx'), 'channel_sessions', ['identity_id'], unique=False)
    op.create_index(op.f('channel_sessions_platform_chat_id_idx'), 'channel_sessions', ['platform_chat_id'], unique=False)
    op.drop_index(op.f('ix_chat_files_user_id'), table_name='chat_files')
    op.create_index(op.f('chat_files_user_id_idx'), 'chat_files', ['user_id'], unique=False)
    op.drop_index(op.f('ix_conversation_shares_conversation_id'), table_name='conversation_shares')
    op.drop_index(op.f('ix_conversation_shares_shared_with'), table_name='conversation_shares')
    op.create_index(op.f('conversation_shares_conversation_id_idx'), 'conversation_shares', ['conversation_id'], unique=False)
    op.create_index(op.f('conversation_shares_shared_with_idx'), 'conversation_shares', ['shared_with'], unique=False)
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('conversations_organization_id_idx'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('conversations_user_id_idx'), 'conversations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_custom_instructions_user_id'), table_name='custom_instructions')
    op.create_index(op.f('custom_instructions_user_id_idx'), 'custom_instructions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.create_index(op.f('insights_user_id_idx'), 'insights', ['user_id'], unique=False)
    op.drop_index(op.f('ix_invitation_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitation_org_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitation_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitation_token'), table_name='invitations')
    op.drop_constraint(op.f('uq_invitation_token'), 'invitations', type_='unique')
    op.create_index(op.f('invitations_email_idx'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('invitations_organization_id_idx'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('invitations_status_idx'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('invitations_token_idx'), 'invitations', ['token'], unique=True)
    op.drop_index(op.f('ix_knowledge_bases_collection_name'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_organization_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_owner_user_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_scope'), table_name='knowledge_bases')
    op.create_index(op.f('knowledge_bases_collection_name_idx'), 'knowledge_bases', ['collection_name'], unique=False)
    op.create_index(op.f('knowledge_bases_organization_id_idx'), 'knowledge_bases', ['organization_id'], unique=False)
    op.create_index(op.f('knowledge_bases_owner_user_id_idx'), 'knowledge_bases', ['owner_user_id'], unique=False)
    op.create_index(op.f('knowledge_bases_scope_idx'), 'knowledge_bases', ['scope'], unique=False)
    op.drop_index(op.f('ix_message_ratings_message_id'), table_name='message_ratings')
    op.drop_index(op.f('ix_message_ratings_user_id'), table_name='message_ratings')
    op.create_index(op.f('message_ratings_message_id_idx'), 'message_ratings', ['message_id'], unique=False)
    op.create_index(op.f('message_ratings_user_id_idx'), 'message_ratings', ['user_id'], unique=False)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('messages_conversation_id_idx'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_note_links_source_note_id'), table_name='note_links')
    op.drop_index(op.f('ix_note_links_target_note_id'), table_name='note_links')
    op.create_index(op.f('note_links_source_note_id_idx'), 'note_links', ['source_note_id'], unique=False)
    op.create_index(op.f('note_links_target_note_id_idx'), 'note_links', ['target_note_id'], unique=False)
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.create_index(op.f('notes_user_id_idx'), 'notes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_org_member_org_id'), table_name='organization_members')
    op.drop_index(op.f('ix_org_member_user_id'), table_name='organization_members')
    op.create_index(op.f('organization_members_organization_id_idx'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('organization_members_user_id_idx'), 'organization_members', ['user_id'], unique=False)
    op.drop_index(op.f('ix_organization_created_by'), table_name='organizations')
    op.drop_index(op.f('ix_organization_is_personal'), table_name='organizations')
    op.drop_index(op.f('ix_organization_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organization_stripe_customer'), table_name='organizations')
    op.drop_index(op.f('ix_organization_tier'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_stripe_subscription_id'), table_name='organizations')
    op.drop_constraint(op.f('uq_organization_slug'), 'organizations', type_='unique')
    op.create_index(op.f('organizations_created_by_user_id_idx'), 'organizations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('organizations_is_personal_idx'), 'organizations', ['is_personal'], unique=False)
    op.create_index(op.f('organizations_slug_idx'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('organizations_stripe_customer_id_idx'), 'organizations', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('organizations_stripe_subscription_id_idx'), 'organizations', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('organizations_subscription_tier_idx'), 'organizations', ['subscription_tier'], unique=False)
    op.drop_index(op.f('ix_plan_code'), table_name='plan')
    op.drop_index(op.f('ix_price_stripe_price_id'), table_name='price')
    op.drop_constraint(op.f('price_stripe_price_id_key'), 'price', type_='unique')
    op.create_index(op.f('price_stripe_price_id_idx'), 'price', ['stripe_price_id'], unique=True)
    op.drop_index(op.f('ix_rag_documents_collection_name'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_knowledge_base_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_organization_id'), table_name='rag_documents')
    op.create_index(op.f('rag_documents_collection_name_idx'), 'rag_documents', ['collection_name'], unique=False)
    op.create_index(op.f('rag_documents_knowledge_base_id_idx'), 'rag_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('rag_documents_organization_id_idx'), 'rag_documents', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.create_index(op.f('sessions_refresh_token_hash_idx'), 'sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('sessions_user_id_idx'), 'sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_sync_logs_collection_name'), table_name='sync_logs')
    op.create_index(op.f('sync_logs_collection_name_idx'), 'sync_logs', ['collection_name'], unique=False)
    op.drop_index(op.f('ix_sync_sources_collection_name'), table_name='sync_sources')
    op.create_index(op.f('sync_sources_collection_name_idx'), 'sync_sources', ['collection_name'], unique=False)
    op.drop_index(op.f('ix_tool_calls_message_id'), table_name='tool_calls')
    op.create_index(op.f('tool_calls_message_id_idx'), 'tool_calls', ['message_id'], unique=False)
    op.drop_index(op.f('ix_user_slash_commands_user_id'), table_name='user_slash_commands')
    op.create_index(op.f('user_slash_commands_user_id_idx'), 'user_slash_commands', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_slash_commands_user_id_idx'), table_name='user_slash_commands')
    op.create_index(op.f('ix_user_slash_commands_user_id'), 'user_slash_commands', ['user_id'], unique=False)
    op.drop_index(op.f('tool_calls_message_id_idx'), table_name='tool_calls')
    op.create_index(op.f('ix_tool_calls_message_id'), 'tool_calls', ['message_id'], unique=False)
    op.drop_index(op.f('sync_sources_collection_name_idx'), table_name='sync_sources')
    op.create_index(op.f('ix_sync_sources_collection_name'), 'sync_sources', ['collection_name'], unique=False)
    op.drop_index(op.f('sync_logs_collection_name_idx'), table_name='sync_logs')
    op.create_index(op.f('ix_sync_logs_collection_name'), 'sync_logs', ['collection_name'], unique=False)
    op.drop_index(op.f('sessions_user_id_idx'), table_name='sessions')
    op.drop_index(op.f('sessions_refresh_token_hash_idx'), table_name='sessions')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=False)
    op.drop_index(op.f('rag_documents_organization_id_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_knowledge_base_id_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_collection_name_idx'), table_name='rag_documents')
    op.create_index(op.f('ix_rag_documents_organization_id'), 'rag_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_knowledge_base_id'), 'rag_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_collection_name'), 'rag_documents', ['collection_name'], unique=False)
    op.drop_index(op.f('price_stripe_price_id_idx'), table_name='price')
    op.create_unique_constraint(op.f('price_stripe_price_id_key'), 'price', ['stripe_price_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_price_stripe_price_id'), 'price', ['stripe_price_id'], unique=False)
    op.create_index(op.f('ix_plan_code'), 'plan', ['code'], unique=False)
    op.drop_index(op.f('organizations_subscription_tier_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_stripe_subscription_id_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_stripe_customer_id_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_slug_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_is_personal_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_created_by_user_id_idx'), table_name='organizations')
    op.create_unique_constraint(op.f('uq_organization_slug'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_organizations_stripe_subscription_id'), 'organizations', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_organization_tier'), 'organizations', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_organization_stripe_customer'), 'organizations', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_organization_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organization_is_personal'), 'organizations', ['is_personal'], unique=False)
    op.create_index(op.f('ix_organization_created_by'), 'organizations', ['created_by_user_id'], unique=False)
    op.drop_index(op.f('organization_members_user_id_idx'), table_name='organization_members')
    op.drop_index(op.f('organization_members_organization_id_idx'), table_name='organization_members')
    op.create_index(op.f('ix_org_member_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_org_member_org_id'), 'organization_members', ['organization_id'], unique=False)
    op.drop_index(op.f('notes_user_id_idx'), table_name='notes')
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.drop_index(op.f('note_links_target_note_id_idx'), table_name='note_links')
    op.drop_index(op.f('note_links_source_note_id_idx'), table_name='note_links')
    op.create_index(op.f('ix_note_links_target_note_id'), 'note_links', ['target_note_id'], unique=False)
    op.create_index(op.f('ix_note_links_source_note_id'), 'note_links', ['source_note_id'], unique=False)
    op.drop_index(op.f('messages_conversation_id_idx'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('message_ratings_user_id_idx'), table_name='message_ratings')
    op.drop_index(op.f('message_ratings_message_id_idx'), table_name='message_ratings')
    op.create_index(op.f('ix_message_ratings_user_id'), 'message_ratings', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_ratings_message_id'), 'message_ratings', ['message_id'], unique=False)
    op.drop_index(op.f('knowledge_bases_scope_idx'), table_name='knowledge_bases')
    op.drop_index(op.f('knowledge_bases_owner_user_id_idx'), table_name='knowledge_bases')
    op.drop_index(op.f('knowledge_bases_organization_id_idx'), table_name='knowledge_bases')
    op.drop_index(op.f('knowledge_bases_collection_name_idx'), table_name='knowledge_bases')
    op.create_index(op.f('ix_knowledge_bases_scope'), 'knowledge_bases', ['scope'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_owner_user_id'), 'knowledge_bases', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_organization_id'), 'knowledge_bases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_collection_name'), 'knowledge_bases', ['collection_name'], unique=False)
    op.drop_index(op.f('invitations_token_idx'), table_name='invitations')
    op.drop_index(op.f('invitations_status_idx'), table_name='invitations')
    op.drop_index(op.f('invitations_organization_id_idx'), table_name='invitations')
    op.drop_index(op.f('invitations_email_idx'), table_name='invitations')
    op.create_unique_constraint(op.f('uq_invitation_token'), 'invitations', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_invitation_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitation_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitation_org_id'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitation_email'), 'invitations', ['email'], unique=False)
    op.drop_index(op.f('insights_user_id_idx'), table_name='insights')
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.drop_index(op.f('custom_instructions_user_id_idx'), table_name='custom_instructions')
    op.create_index(op.f('ix_custom_instructions_user_id'), 'custom_instructions', ['user_id'], unique=False)
    op.drop_index(op.f('conversations_user_id_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_organization_id_idx'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.drop_index(op.f('conversation_shares_shared_with_idx'), table_name='conversation_shares')
    op.drop_index(op.f('conversation_shares_conversation_id_idx'), table_name='conversation_shares')
    op.create_index(op.f('ix_conversation_shares_shared_with'), 'conversation_shares', ['shared_with'], unique=False)
    op.create_index(op.f('ix_conversation_shares_conversation_id'), 'conversation_shares', ['conversation_id'], unique=False)
    op.drop_index(op.f('chat_files_user_id_idx'), table_name='chat_files')
    op.create_index(op.f('ix_chat_files_user_id'), 'chat_files', ['user_id'], unique=False)
    op.drop_index(op.f('channel_sessions_platform_chat_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_identity_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_conversation_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_bot_id_idx'), table_name='channel_sessions')
    op.create_index(op.f('ix_channel_sessions_platform_chat_id'), 'channel_sessions', ['platform_chat_id'], unique=False)
    op.create_index(op.f('ix_channel_sessions_identity_id'), 'channel_sessions', ['identity_id'], unique=False)
    op.create_index(op.f('ix_channel_sessions_conversation_id'), 'channel_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_channel_sessions_bot_id'), 'channel_sessions', ['bot_id'], unique=False)
    op.drop_index(op.f('channel_identities_user_id_idx'), table_name='channel_identities')
    op.drop_index(op.f('channel_identities_platform_user_id_idx'), table_name='channel_identities')
    op.drop_index(op.f('channel_identities_platform_idx'), table_name='channel_identities')
    op.create_index(op.f('ix_channel_identities_user_id'), 'channel_identities', ['user_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_platform_user_id'), 'channel_identities', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_platform'), 'channel_identities', ['platform'], unique=False)
    op.drop_index(op.f('channel_bots_platform_idx'), table_name='channel_bots')
    op.create_index(op.f('ix_channel_bots_platform'), 'channel_bots', ['platform'], unique=False)
    op.drop_index(op.f('app_admin_audit_logs_organization_id_idx'), table_name='app_admin_audit_logs')
    op.drop_index(op.f('app_admin_audit_logs_actor_user_id_idx'), table_name='app_admin_audit_logs')
    op.drop_index(op.f('app_admin_audit_logs_action_idx'), table_name='app_admin_audit_logs')
    op.create_index(op.f('ix_audit_organization_id'), 'app_admin_audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_actor_user_id'), 'app_admin_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_action'), 'app_admin_audit_logs', ['action'], unique=False)
    op.drop_index(op.f('api_keys_user_id_idx'), table_name='api_keys')
    op.drop_index(op.f('api_keys_key_prefix_idx'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=True)
    op.add_column('agent_memories', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('agent_memories_user_id_idx'), table_name='agent_memories')
    op.create_index(op.f('ix_agent_memories_user_id'), 'agent_memories', ['user_id'], unique=False)
    op.create_table('stripe_event',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('stripe_event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_event_pkey')),
    sa.UniqueConstraint('stripe_event_id', name=op.f('stripe_event_stripe_event_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stripe_event_stripe_event_id'), 'stripe_event', ['stripe_event_id'], unique=False)
    op.create_index(op.f('ix_stripe_event_event_type'), 'stripe_event', ['event_type'], unique=False)
    op.create_table('rag_sb_353de8cecd9a4ed69498d86f2fedb673',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parent_doc_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_sb_353de8cecd9a4ed69498d86f2fedb673_pkey'))
    )
    op.create_index(op.f('rag_sb_353de8cecd9a4ed69498d86f2fedb673_embedding_idx'), 'rag_sb_353de8cecd9a4ed69498d86f2fedb673', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('stripe_item_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('seats_quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('subscription_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], name=op.f('subscription_price_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_pkey')),
    sa.UniqueConstraint('organization_id', name=op.f('subscription_organization_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('subscription_stripe_subscription_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('subscription_status_idx'), 'subscription', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_subscription_id'), 'subscription', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_customer_id'), 'subscription', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscription_organization_id'), 'subscription', ['organization_id'], unique=False)
    # ### end Alembic commands ###
