
"""add custom instructions

Revision ID: c9c64b0c85d1
Revises: 0018_user_slash_commands
Create Date: 2026-06-07 12:15:38.514516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9c64b0c85d1'
down_revision: Union[str, None] = '0018_user_slash_commands'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('app_admin_audit_logs_pkey'))
    )
    op.create_index(op.f('app_admin_audit_logs_action_idx'), 'app_admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('app_admin_audit_logs_actor_user_id_idx'), 'app_admin_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('app_admin_audit_logs_organization_id_idx'), 'app_admin_audit_logs', ['organization_id'], unique=False)
    op.create_table('channel_bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_encrypted', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('webhook_mode', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('access_policy', sa.JSON(), nullable=False),
    sa.Column('ai_model_override', sa.String(length=255), nullable=True),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_bots_pkey'))
    )
    op.create_index(op.f('channel_bots_platform_idx'), 'channel_bots', ['platform'], unique=False)
    op.create_table('sync_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=20), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('sync_mode', sa.String(length=20), nullable=False),
    sa.Column('schedule_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_sources_pkey'))
    )
    op.create_index(op.f('sync_sources_collection_name_idx'), 'sync_sources', ['collection_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_app_admin', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_table('channel_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_user_id', sa.String(length=100), nullable=False),
    sa.Column('platform_username', sa.String(length=100), nullable=True),
    sa.Column('platform_display_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('link_code', sa.String(length=10), nullable=True),
    sa.Column('link_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('channel_identities_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_identities_pkey')),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_channel_identity_platform_user')
    )
    op.create_index(op.f('channel_identities_platform_idx'), 'channel_identities', ['platform'], unique=False)
    op.create_index(op.f('channel_identities_platform_user_id_idx'), 'channel_identities', ['platform_user_id'], unique=False)
    op.create_index(op.f('channel_identities_user_id_idx'), 'channel_identities', ['user_id'], unique=False)
    op.create_table('custom_instructions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('custom_instructions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_instructions_pkey'))
    )
    op.create_index(op.f('custom_instructions_user_id_idx'), 'custom_instructions', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('subscription_tier', sa.String(length=32), nullable=False),
    sa.Column('seats_limit', sa.Integer(), nullable=True),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('organizations_created_by_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey'))
    )
    op.create_index(op.f('organizations_created_by_user_id_idx'), 'organizations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('organizations_is_personal_idx'), 'organizations', ['is_personal'], unique=False)
    op.create_index(op.f('organizations_slug_idx'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('organizations_stripe_customer_id_idx'), 'organizations', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('organizations_stripe_subscription_id_idx'), 'organizations', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('organizations_subscription_tier_idx'), 'organizations', ['subscription_tier'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('sessions_refresh_token_hash_idx'), 'sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('sessions_user_id_idx'), 'sessions', ['user_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('sync_source_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('ingested', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sync_source_id'], ['sync_sources.id'], name=op.f('sync_logs_sync_source_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_logs_pkey'))
    )
    op.create_index(op.f('sync_logs_collection_name_idx'), 'sync_logs', ['collection_name'], unique=False)
    op.create_table('user_slash_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_slash_commands_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_slash_commands_pkey')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_slash_commands_user_name')
    )
    op.create_index(op.f('user_slash_commands_user_id_idx'), 'user_slash_commands', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('active_knowledge_base_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('conversations_organization_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('conversations_organization_id_idx'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('conversations_user_id_idx'), 'conversations', ['user_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('invitations_accepted_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('invitations_invited_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('invitations_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitations_pkey'))
    )
    op.create_index(op.f('invitations_email_idx'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('invitations_organization_id_idx'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('invitations_status_idx'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('invitations_token_idx'), 'invitations', ['token'], unique=True)
    op.create_index('uq_pending_invitation', 'invitations', ['organization_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('knowledge_bases_organization_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('knowledge_bases_owner_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_bases_pkey'))
    )
    op.create_index(op.f('knowledge_bases_collection_name_idx'), 'knowledge_bases', ['collection_name'], unique=False)
    op.create_index(op.f('knowledge_bases_organization_id_idx'), 'knowledge_bases', ['organization_id'], unique=False)
    op.create_index(op.f('knowledge_bases_owner_user_id_idx'), 'knowledge_bases', ['owner_user_id'], unique=False)
    op.create_index(op.f('knowledge_bases_scope_idx'), 'knowledge_bases', ['scope'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('organization_members_invited_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('organization_members_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('organization_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_members_pkey')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    op.create_index('ix_org_member_org_role', 'organization_members', ['organization_id', 'role'], unique=False)
    op.create_index(op.f('organization_members_organization_id_idx'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('organization_members_user_id_idx'), 'organization_members', ['user_id'], unique=False)
    op.create_table('channel_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('platform_chat_id', sa.String(length=100), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['channel_bots.id'], name=op.f('channel_sessions_bot_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('channel_sessions_conversation_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['channel_identities.id'], name=op.f('channel_sessions_identity_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_sessions_pkey')),
    sa.UniqueConstraint('bot_id', 'platform_chat_id', name='uq_channel_session_bot_chat')
    )
    op.create_index(op.f('channel_sessions_bot_id_idx'), 'channel_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('channel_sessions_conversation_id_idx'), 'channel_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('channel_sessions_identity_id_idx'), 'channel_sessions', ['identity_id'], unique=False)
    op.create_index(op.f('channel_sessions_platform_chat_id_idx'), 'channel_sessions', ['platform_chat_id'], unique=False)
    op.create_table('conversation_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.UUID(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_shares_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], name=op.f('conversation_shares_shared_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], name=op.f('conversation_shares_shared_with_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_shares_pkey')),
    sa.UniqueConstraint('conversation_id', 'shared_with', name='uq_share_conv_user'),
    sa.UniqueConstraint('share_token', name=op.f('conversation_shares_share_token_key'))
    )
    op.create_index(op.f('conversation_shares_conversation_id_idx'), 'conversation_shares', ['conversation_id'], unique=False)
    op.create_index(op.f('conversation_shares_shared_with_idx'), 'conversation_shares', ['shared_with'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('messages_conversation_id_idx'), 'messages', ['conversation_id'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('filetype', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('vector_document_id', sa.String(length=255), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name=op.f('rag_documents_knowledge_base_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('rag_documents_organization_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_documents_pkey'))
    )
    op.create_index(op.f('rag_documents_collection_name_idx'), 'rag_documents', ['collection_name'], unique=False)
    op.create_index(op.f('rag_documents_knowledge_base_id_idx'), 'rag_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('rag_documents_organization_id_idx'), 'rag_documents', ['organization_id'], unique=False)
    op.create_table('chat_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('chat_files_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_files_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_files_pkey'))
    )
    op.create_index(op.f('chat_files_user_id_idx'), 'chat_files', ['user_id'], unique=False)
    op.create_table('message_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating IN (1, -1)', name=op.f('message_ratings_ck_rating_value_check')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_ratings_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_ratings_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user_rating')
    )
    op.create_index(op.f('message_ratings_message_id_idx'), 'message_ratings', ['message_id'], unique=False)
    op.create_index(op.f('message_ratings_user_id_idx'), 'message_ratings', ['user_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('tool_calls_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tool_calls_pkey'))
    )
    op.create_index(op.f('tool_calls_message_id_idx'), 'tool_calls', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tool_calls_message_id_idx'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('message_ratings_user_id_idx'), table_name='message_ratings')
    op.drop_index(op.f('message_ratings_message_id_idx'), table_name='message_ratings')
    op.drop_table('message_ratings')
    op.drop_index(op.f('chat_files_user_id_idx'), table_name='chat_files')
    op.drop_table('chat_files')
    op.drop_index(op.f('rag_documents_organization_id_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_knowledge_base_id_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_collection_name_idx'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('messages_conversation_id_idx'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('conversation_shares_shared_with_idx'), table_name='conversation_shares')
    op.drop_index(op.f('conversation_shares_conversation_id_idx'), table_name='conversation_shares')
    op.drop_table('conversation_shares')
    op.drop_index(op.f('channel_sessions_platform_chat_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_identity_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_conversation_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_bot_id_idx'), table_name='channel_sessions')
    op.drop_table('channel_sessions')
    op.drop_index(op.f('organization_members_user_id_idx'), table_name='organization_members')
    op.drop_index(op.f('organization_members_organization_id_idx'), table_name='organization_members')
    op.drop_index('ix_org_member_org_role', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('knowledge_bases_scope_idx'), table_name='knowledge_bases')
    op.drop_index(op.f('knowledge_bases_owner_user_id_idx'), table_name='knowledge_bases')
    op.drop_index(op.f('knowledge_bases_organization_id_idx'), table_name='knowledge_bases')
    op.drop_index(op.f('knowledge_bases_collection_name_idx'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('uq_pending_invitation', table_name='invitations', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('invitations_token_idx'), table_name='invitations')
    op.drop_index(op.f('invitations_status_idx'), table_name='invitations')
    op.drop_index(op.f('invitations_organization_id_idx'), table_name='invitations')
    op.drop_index(op.f('invitations_email_idx'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('conversations_user_id_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_organization_id_idx'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('user_slash_commands_user_id_idx'), table_name='user_slash_commands')
    op.drop_table('user_slash_commands')
    op.drop_index(op.f('sync_logs_collection_name_idx'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('sessions_user_id_idx'), table_name='sessions')
    op.drop_index(op.f('sessions_refresh_token_hash_idx'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('organizations_subscription_tier_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_stripe_subscription_id_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_stripe_customer_id_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_slug_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_is_personal_idx'), table_name='organizations')
    op.drop_index(op.f('organizations_created_by_user_id_idx'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('custom_instructions_user_id_idx'), table_name='custom_instructions')
    op.drop_table('custom_instructions')
    op.drop_index(op.f('channel_identities_user_id_idx'), table_name='channel_identities')
    op.drop_index(op.f('channel_identities_platform_user_id_idx'), table_name='channel_identities')
    op.drop_index(op.f('channel_identities_platform_idx'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('sync_sources_collection_name_idx'), table_name='sync_sources')
    op.drop_table('sync_sources')
    op.drop_index(op.f('channel_bots_platform_idx'), table_name='channel_bots')
    op.drop_table('channel_bots')
    op.drop_index(op.f('app_admin_audit_logs_organization_id_idx'), table_name='app_admin_audit_logs')
    op.drop_index(op.f('app_admin_audit_logs_actor_user_id_idx'), table_name='app_admin_audit_logs')
    op.drop_index(op.f('app_admin_audit_logs_action_idx'), table_name='app_admin_audit_logs')
    op.drop_table('app_admin_audit_logs')
    # ### end Alembic commands ###
